### ISSUE TITLE
Cannot import DS1 into ESPHome

### ISSUE THREAD

**Issue by Sleepy-Orange** [screekworkshop/Screek-Distance-Sensor#1]
Hi, I'm trying to use ESPHome in Home Assistant to compile a firmware, but got the following errors:
```
INFO ESPHome 2025.3.2
INFO Reading configuration /config/esphome/shower-screek-ds1.yaml...
Failed config

external_components: [source /data/packages/49fcc777/distance-sensor-ds1-github-stable.yaml:59]
  - 
    Source is not a file system path, in expected github://username/name[@branch-or-tag] or github://pr#1234 format!.
    source: screek-components
```

My ESPHome yaml config:
```
substitutions:
  name: screek-ds1
  friendly_name: Screek DS1

packages:
  Screek.Distance-Sensor-DS1: github://screekworkshop/Screek-Distance-Sensor/distance-sensor-ds1-github-stable.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

api:
  encryption:
    key: !secret screek_ds1_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

It seems to be caused by https://github.com/screekworkshop/Screek-Distance-Sensor/blob/84ebd004464f45fcd81f75b550432a62c3bfd88c/distance-sensor-ds1-github-stable.yaml#L59 using the external component in local format: https://esphome.io/components/external_components.html#external-components

Since imported config doesn't have the local external components, could you please update the line to use a GitHub source instead? Thanks.
